apiVersion: v1
data:
  nginx.conf: |
    events {
      worker_connections  4096;  ## Default: 1024
    }
    http {
      server {
        listen 80;
        client_max_body_size 60M;

        gzip on;
        gzip_types  text/plain text/html application/xml;
        gzip_proxied any;
        location =/ {
          proxy_pass http://{{ .Values.model }}.{{ .Values.app }}.svc.cluster.local:{{ .Values.port }}/;
        }
        location ~ "^(.*)/data/" {
          rewrite "^(.*)/data/(.*)$" /data/$2 break;
          proxy_pass  http://{{ .Values.model }}.{{ .Values.app }}.svc.cluster.local:{{ .Values.port }}
        }
        location /data/ {
          proxy_pass http://{{ .Values.model }}.{{ .Values.app }}.svc.cluster.local:{{ .Values.port }}/data/;
        }
        location / {
              try_files $uri $uri/ /;
        }
      }
    }
kind: ConfigMap
metadata:
  name: router
