apiVersion: v1
data:
  nginx.conf: |
    events {
      worker_connections  4096;  ## Default: 1024
    }
    http {
      server {
        listen 80;
        client_max_body_size 60M;

        gzip on;
        gzip_types  text/plain text/html application/xml;
        gzip_proxied any;
        location / {
          proxy_pass http://controller.{{ .Release.Namespace }}.svc.cluster.local:8888/;
        }
        location /api/v1/proxy/namespaces/{{ .Release.Namespace }}/services/nginx-controller:80/ {
            proxy_pass http://controller.{{ .Release.Namespace }}.svc.cluster.local:8888/;
         }
      }
    }
kind: ConfigMap
metadata:
  name: router