apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image:  nginx:1.10.1
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx
          name: config
      volumes:
      - name: config
        configMap:
          name: router
          items:
          - key: nginx.conf
            path: nginx.conf
