apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image:  kuberlab/zappos-ui:latest
        ports:
        - containerPort: 8888
        env:
          - name: API_URL
            value: "http://{{ .Values.model }}.{{ .Values.app }}.svc.cluster.local:{{ .Values.port }}"
