apiVersion: v1
kind: Service
metadata:
  name: nginx-controller
  labels:
    app: controller
    component: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: controller
    component: nginx