apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    app: controller
spec:
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: controller